### ISSUE TITLE
leap year's bug

### ISSUE THREAD

**Issue by RomanKV-1** [FlymeDllVa/telebot-calendar#2]
Из-за того что 2020 год високосный день недели отстает от даты. Например 30.03.2020 указывается как воскресенье.
![r-b_calendar](https://user-images.githubusercontent.com/58108797/77893312-6f7a0400-727c-11ea-9b60-583f233cdf96.png)

**Comment by flymedllva** [comment]
Проверил, у меня вроде все хорошо. 
У Вас версия последнего коммита? 
![image](https://user-images.githubusercontent.com/33265875/77911067-df968300-7298-11ea-8102-1d359f295ee6.jpeg)

**Comment by RomanKV-1** [comment]
Да, последняя.
Ставил уже через pip. Как он определяет английские название дней недели выводить или русские? По серверу? Может это из - за того что он определяет Sunday  как первый день недели?
